### PR TITLE
Fix null-morph-to-association branch with rebase

### PR DESCRIPTION
**Pull request by ebramanti**
This fix will allow for a clean rebase instead of the merge I used to update the `null-morph-to-association` branch. This will mean I have to overwrite this current branch. However, I will store a backup before I perform this push, and will check if it breaks any projects before deleting this old fix branch.

This rebase will also make it much easier to get your PR reviewed and possibly merged into Bookshelf (now that I'm a contributor :wink:).

### CODE REVIEW

**Comment by ebramanti** [comment]
@patbenatar It's golden! Seems the overwrite worked great. I was able to maintain your commit without breaking any of the functionality you added. Hope this is OK with you!

**Comment by patbenatar** [comment]
@jadengore :+1: thanks!

**Comment by ebramanti** [comment]
@patbenatar Gah! I just looked at your PR to Bookshelf and it seems 32 files have been changed. Darn! Will have to look into fixing this later.

**Comment by patbenatar** [comment]
@jadengore :(

**Pull request merged**
