### PR TITLE
Bump custom Bookshelf branch to v0.8.1

### PR DESCRIPTION
**Pull request by ebramanti**
I noticed while working through some Bookshelf issues that we haven't updated the Bookshelf dependencies for our needs. I've plopped commits up to the latest release (0.8.1) on top of your modification.

I haven't been able to get tests to run right locally for me, so I am hoping their Travis integration picks up this branch.

### CODE REVIEW

**Comment by patbenatar** [comment]
@jadengore did you run into any conflicts when merging?

**Comment by ebramanti** [comment]
Yes, they changed the `/lib/relations` file that you modified. I'll try and run tests locally again before we merge this.

**Comment by ebramanti** [comment]
@patbenatar I got a green light on Bookshelf's tests:

**Comment by patbenatar** [comment]
@jadengore Can you try pointing our package.json at this branch and run our app test suite against it?

**Comment by ebramanti** [comment]
@patbenatar On it.

Edit: All tests passing with my Bookshelf branch in the `package.json`. I'm pretty certain this is safe to merge :shipit:

**Comment by patbenatar** [comment]
:shipit: !

**Pull request merged**
